version: '3'

services:
  media-server:
    container_name: chotuve-media-server
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: npm start
    environment:
      - NODE_ENV=dev
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: mongod
