version: '3'

services:
  media-server:
    container_name: chotuve-media-server
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: npm start
    environment:
      - NODE_ENV=${NODE_ENV}
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: mongod
  mongo_test:
    image: mongo
    ports:
      - 27018:27018
    command: mongod --port 27018